# Generated by Django 2.2 on 2020-06-03 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timeSheetApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_status',
        ),
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('S', 'Started'), ('O', 'On going'), ('C', 'Completed')], default='S', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='ending_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='starting_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='task_description',
            field=models.TextField(null=True),
        ),
    ]
