# Generated by Django 2.2 on 2020-06-03 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeSheetApp', '0002_auto_20200603_1936'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Timesheet',
        ),
    ]
