# Generated by Django 2.2 on 2020-06-03 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeSheetApp', '0003_auto_20200603_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_members',
            field=models.ManyToManyField(to='timeSheetApp.User'),
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeSheetApp.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeSheetApp.User')),
            ],
        ),
    ]
