# Generated by Django 2.2 on 2020-06-03 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeSheetApp', '0004_auto_20200603_2203'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_members',
        ),
    ]
