# Generated by Django 2.2 on 2020-06-03 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeSheetApp', '0005_auto_20200603_2211'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Assigned_Project_Member',
        ),
    ]
