# Generated by Django 2.2 on 2020-06-04 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeSheetApp', '0006_auto_20200603_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeSheetApp.Project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timeSheetApp.User')),
            ],
        ),
        migrations.DeleteModel(
            name='Assigned_Project_Member',
        ),
    ]
