# Generated by Django 2.2 on 2020-06-05 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeSheetApp', '0009_auto_20200604_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='working_hours_end',
        ),
        migrations.RemoveField(
            model_name='user',
            name='working_hours_start',
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='timeSheetApp.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timesheet',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='timeSheetApp.User'),
            preserve_default=False,
        ),
       
    ]
