# Generated by Django 2.2 on 2020-06-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeSheetApp', '0010_auto_20200605_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='user', max_length=250),
        ),
        
    ]
