# Generated by Django 3.0.6 on 2020-06-06 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeSheetApp', '0012_auto_20200606_2125'),
    ]

    operations = [
       
    ]
